# Generated by Django 5.1.1 on 2024-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
