# Generated by Django 5.1.1 on 2024-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0006_remove_trainer_password_remove_trainer_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='class_images/'),
        ),
    ]
