# Generated by Django 5.1.1 on 2024-10-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0007_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
