# Generated by Django 5.1.1 on 2024-10-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0008_alter_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
