# Generated by Django 5.1.1 on 2024-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0009_alter_class_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
