# Generated by Django 5.1.1 on 2024-10-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0010_alter_schedule_booked_seats_alter_schedule_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
