# Generated by Django 5.1.1 on 2024-10-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0011_alter_class_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
