# Generated by Django 5.1.1 on 2024-10-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0012_alter_membership_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='free_classes_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='quota',
            field=models.IntegerField(default=0),
        ),
    ]
