# Generated by Django 5.1.1 on 2024-10-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitmark', '0014_booking_used_quota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
